### ISSUE TITLE
mergeResolvers recursive crash

### ISSUE THREAD

**Issue by lifeiscontent** [okgrow/merge-graphql-schemas#101] opened 2017-10-23 16:12 UTC
using graphql-tools to merge resolvers I get an error when merging the types from onTypeConflict.

``` js
import {
  makeRemoteExecutableSchema,
  introspectSchema,
  mergeSchemas
} from 'graphql-tools';
import { mergeResolvers } from 'merge-graphql-schemas';
import { HttpLink } from 'apollo-link-http';
import fetch from 'node-fetch';

const makeSchema = async (uri, index) => {
  const link = new HttpLink({ uri, fetch });
  const schema = await introspectSchema(link);

  return makeRemoteExecutableSchema({
    schema,
    link
  });
};

export async function makeMergedSchema(uris) {
  const schemas = await Promise.all(
    uris.map((uri, index) => makeSchema(uri, index))
  );

  schemas.push(`
    extend type Post {
      author: Author
    }
  `);

  return mergeSchemas({
    schemas,
    resolvers: mergeInfo => ({
      Post: {
        author: {
          fragment: 'fragment PostFragment on Post { authorId }',
          resolve(parent, args, context, info) {
            return mergeInfo.delegate(
              'query',
              'authorById',
              {
                id: parent.authorId
              },
              context,
              info
            );
          }
        }
      }
    }),
    onTypeConflict(left, right) {
      const merged = mergeResolvers([left, right]);
      // when merged gets to the post type in my schema, it crashes
      return merged;
    }
  });
}
```

``` json
{
  "error": {
    "message": "Maximum call stack size exceeded",
    "stack": "RangeError: Maximum call stack size exceeded
    at deepmerge (/usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1159:19)
    at /usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1153:32
    at Array.forEach (<anonymous>)
    at mergeObject (/usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1149:25)
    at deepmerge (/usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1171:16)
    at /usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1153:32
    at Array.forEach (<anonymous>)
    at mergeObject (/usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1149:25)
    at deepmerge (/usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1171:16)
    at /usr/src/app/node_modules/merge-graphql-schemas/dist/index.cjs.js:1153:32"
   }
}
```

**Comment by cfnelson** [comment] 2017-11-02 05:31
@lifeiscontent I apologise for not responding sooner. Are you still having the issue reported above or did you resolve/come up with a work around?

Are the resolvers you are trying to merge extremely large or contain a lot of nesting/deeply nested objects?

To help us better solve this issue would you be able to share an example of the two resolvers you are trying merge so we can test against ourselves? Or a minimal reproduction with two schemas where this is occurring?

The error you report suggests/points to a memory issue occurring whilst we use `deepmerge`. I suspect that potentially the resolvers/schema you have might have a cyclic object/structure which is causing the problem.

**Comment by lifeiscontent** [comment] 2017-11-04 06:07
@cfnelson hey! thanks for the response.

You can check out my example project here: https://github.com/lifeiscontent/postgraphql-schema-stitching

if you look at this file https://github.com/lifeiscontent/postgraphql-schema-stitching/blob/master/server/src/schema.js

graphql-tools mergeSchemas function takes an onTypeConflict arg, if you use that with merge-graphql-schemas, you can reproduce the errors.

this example is using docker, so if that's an issue for you, I can try to reduce the test case for you.

**Comment by cfnelson** [comment] 2017-11-13 23:56
@lifeiscontent The bug is related to `deepmerge` and most likely trying to merge a cyclic object/structure. The latest release of `deepmerge` may resolve this issue for you. 

If you are only using this package for `mergeResolvers()` I would recommend switching to using `deepmerge` or a similar npm pkg directly instead of this package.

You can simply replace your `mergeResolvers([left, right]);` line with `merge.all([left, right])` which comes directly from `deepmerge`. You can see [here](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/merge_resolvers.js#L3) that  `mergeResolvers()` is only wrapping `merge.all()`.

**Comment by cfnelson** [comment] 2017-11-17 18:06
Closing for now as the issue is related to `deepmerge` and the two resolvers passed to it.
Happy to continue the discussion further if help is needed. 😄

**Closed by cfnelson** 2017-11-17 18:06 UTC
Labels: question
