### ISSUE TITLE
export default `` in schema crashes app

### ISSUE THREAD

**Issue by locohost** [okgrow/merge-graphql-schemas#88] opened 2017-09-10 14:52 UTC
This drove me crazy for quite a while. Syntax is valid, doesn't seem like anything that would crash the app, but it surely does. You cannot use **export default ` ... `;** (like ALL of your documentation shows) to build your schema file. You MUST use **module.exports = ` .. `;** And don't ever wrap schema in [ ] like a lot of examples show. This also crashes the app.

**Comment by RichardLitt** [comment] 2017-09-11 13:33
Thanks for opening an issue @locohost. Can you point us to your fork or implementation, or provide a test case?

**Comment by cfnelson** [comment] 2017-09-15 15:34
@locohost It sounds like you might be having an issue with `babel`? The scenario you describe is covered by our tests [here](https://github.com/okgrow/merge-graphql-schemas/blob/master/test/merge_types.test.js). 

Are you using babel's [transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) plugin? If you are not using or do not want to use `babel` you should take a look [esm](https://github.com/standard-things/esm) awesome package that enable ES modules in Node 4+.

**Comment by locohost** [comment] 2017-09-15 15:46
I do have babel installed. Maybe I have the wrong version? Or perhaps I'm missing the plugin you mentioned above? I don't remember installing that. I'll take a look when I get home.

Thanks for the replies. And BTW, merge-graphql-schemas is working well for me now with the fix I mentioned in OP. Just this one weird part threw me when setting it up for first time.

**Comment by cfnelson** [comment] 2017-09-15 16:09
@locohost If you want a no fuss setup for ES module support in node, `esm` is worth checking out. I would highly recommend reading the release [blogpost](https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b) for it.

Would love to hear an update on the `babel` setup situation. What version of `babel`/`node` are you using? If you have any issues with setting up that plugin let us know and will be happy to help.

**Comment by cfnelson** [comment] 2017-10-17 16:43
@locohost Closing this issue for now, please let us know if you weren't able to resolve and we can reopen. I suspect the cause was due to your setup for `es modules` and not a bug within the package itself.

**Closed by cfnelson** 2017-10-17 16:43 UTC
Labels: question
