### ISSUE TITLE
TypeError: buildASTSchema.getDescription is not a function

### ISSUE THREAD

**Issue by silkyland** [okgrow/merge-graphql-schemas#111] opened 2017-12-16 12:28 UTC
I got this error 

TypeError: buildASTSchema.getDescription is not a function .

Any help?

**Comment by bermanboris** [comment] 2017-12-17 16:08
You can downgrade version of "graphql" dependency. Version ^0.11.7 is working fine for me!

**Comment by RichardLitt** [comment] 2017-12-22 14:39
@email2vimalraj A PR would be great. For now, the above downgrade should work while we allocate time to process this.

**Comment by RodMachado** [comment] 2017-12-22 15:49
This could be related https://github.com/graphql/graphql-js/pull/1165.
I'll verify if upgrading graphql will fix the problem.

**Comment by RodMachado** [comment] 2017-12-22 19:39
Hey @silkyland and @email2vimalraj 
Apparently `getDescription` function from `buildASTSchema` was no longer being exported since version `0.12.0`. The issue is fixed with this PR https://github.com/graphql/graphql-js/commit/8173c24dba61c5e032e4abd518729a5591b3076c but it is not available yet. It will probably be published in version `0.12.4` (I thought this was included in version `0.12.3`, but it was not).

The solution for now is to use graphql version `0.11.7`.

**Comment by email2vimalraj** [comment] 2017-12-26 09:32
Okay, then we have to wait till 0.12.4 is out. Thanks for the update.



Thanks
Vimalraj
http://vimalselvam.com
https://www.gitshowcase.com/email2vimalraj

**Comment by Rajeshr34** [comment] 2018-01-19 18:54
Works on latest GraphQL
Fix: yarn add graphql@git://github.com/graphql/graphql-js.git#npm

**Comment by j** [comment] 2018-01-23 01:17
No activity on this repo for a while.  Wish it'd work out of the box with `graphql-yoga`

**Comment by RichardLitt** [comment] 2018-01-23 01:22
@j We're here. Is it not working with `graphql-yoga` because of this issue? I'd be happy to escalate it.

**Comment by beebase** [comment] 2018-01-23 12:25
I'm having same error "TypeError: buildASTSchema.getDescription is not a function ."
with these versions
```
"graphql": "^0.12.3",
"graphql-yoga": "1.2.0",
"merge-graphql-schemas": "^1.4.0",
```
downgrading graphql to 0.11.7 seems to work but I have another question

schema.grapql  imports a Type from another graphql file
![image](https://user-images.githubusercontent.com/446089/35275497-3cc2c7d2-0040-11e8-9d0d-e805a9eed5dd.png)

...which results in this error. I suppose the import is not resolved by merge-graphql-schemas?
Is there another way to achieve this?
![image](https://user-images.githubusercontent.com/446089/35275553-72e2a328-0040-11e8-90ee-fa157759e64a.png)

**Comment by RichardLitt** [comment] 2018-01-23 14:46
@RodMachado Can you offer an update on this one?

**Comment by cfnelson** [comment] 2018-01-23 14:57
@RichardLitt This isn't something we cam fix its due to graphql.js. See above explanation and answer by Rodrigo. @j @beebase `The solution for now is to use graphql version 0.11.7.` or switch to using the github branch instead of the npm pkg -> `Fix: yarn add graphql@git://github.com/graphql/graphql-js.git#npm`

Once `graphql: 0.12.4` is released then this issue will resolve itself by upgrading to that version.

**Comment by RichardLitt** [comment] 2018-01-23 15:00
Thanks for clarifying, @cfnelson. I appreciate it - not sure how I missed that. 👍

**Comment by cfnelson** [comment] 2018-01-23 19:34
@beebase Sorry, I missed the 2nd part of your question. Yes we don't resolve `imports` inside a .graphql file. However `merge-graphql-schemas` should generate a single graphql types and one for your resolvers. Which you would then use to create your schema.

If your still having problems open up a new issue for the graphql-yogo issue you have. If you provide an example of how you are using merge-graphql-schemas we might be able to help.

**Comment by liuuu** [comment] 2018-01-24 02:37
Hi. when I changed to github branch by
`yarn add graphql@git://github.com/graphql/graphql-js.git#npm`

popup: `warning " > merge-graphql-schemas@1.4.0" has incorrect peer dependency "graphql@^0.11.7".`

`npm start`
`
node_modules/graphql/utilities/buildASTSchema.js:188
        throw new Error('Specified ' + operation + ' type "' + typeName + '" not found in document.');
        ^
`
So, what's the problem?

**Comment by beebase** [comment] 2018-01-24 08:36
@cfnelson Thanks, I'll try to explain my problem.
I'm using prisma API, which generates a database API based on types you define in a database model.
so "type User {}" generates createUser, deleteUser, filterUser etc.. in prisma.graphql.
![img2694](https://user-images.githubusercontent.com/446089/35321370-0a824ff2-00e7-11e8-8fa5-bafff6db4edb.jpg)
The schema.graphql is manually written and acts as a public layer in front of the prisma.graphql. (prisma is hidden to clients)
So when I define a public query "feed" (list of posts) I need to import the generated type Post from prisma.
![img2696](https://user-images.githubusercontent.com/446089/35321627-a2292b64-00e7-11e8-9c12-f82c4cbe394f.jpg)
Because # import doesn't work with merge-graphql-schemas, I thought lets just move prisma.graphql into the same directory as schema.graphql so everything gets merged together.
Turns out this doesn't work either, because sometimes you need to define a type twice, which causes a collision when merging.
For instance, type User is defined (to the outside world) in schema.graphql without field "password" but is also auto generated in prisma.graphql with password.
![img2695](https://user-images.githubusercontent.com/446089/35321820-548c9520-00e8-11e8-946b-40328027fe91.jpg)
So the basic problem here is:
We are building a public layer (schema.graphql) that needs to import autogenerated types from prisma.graphql. But not all generated types, because some (like User) are already custom defined in schema.graphql.

**Comment by cfnelson** [comment] 2018-01-24 17:04
@liuuu You may be running into issues if your mixing `yarn` & `npm` together and you didn't clear your `node_modules`/`pkg-lock.json`. From the error message you have the issue you might be running into is dependent on what types you have in your graphql files.  Would need a minimal reproduction to be able to understand the issue your having better.

**Comment by cfnelson** [comment] 2018-01-24 17:15
@beebase If I understand correctly, what you have described is the ability too merge the same two types together (which have been defined in two files). Specifically what you are hoping to achieve is to merge the field definitions together or in your case have some field definitions omitted in your final type definition.

Currently this isn't supported by this package as it comes with various complications. We have a discussion over on [issue #113](https://github.com/okgrow/merge-graphql-schemas/issues/113) which is where I think we should continue this discussion. And would be interested to hear your input on the matter. 

Also to clarify in your `schema.graphql` file contains only your type definitions?

**Comment by beebase** [comment] 2018-01-24 19:41
Thanks, I'll have a look at #113.
And yes, schema.graphql holds the type defs, although eventually this file will be divided into user.grapgql, post.graphql, comment.graphql etc...

**Comment by beebase** [comment] 2018-01-24 19:42
Thanks, I'll have a look at #113.
And yes, schema.graphql holds the type defs. Eventually this file will be divided into user.grapgql, post.graphql, comment.graphql etc...

**Comment by davidjohnbell** [comment] 2018-01-29 19:20
Hello, I am trying to implement your library. When I downgraded graphql to 0.11.7 I get an error when I try to use subscriptions. I can perform queries and get the proper data, but subscriptions seem to throw an error inside the graphiql playground.

```JavaScript
// ./graphql/resolvers/myResolvers.js
module.exports = {
  Query: {
    hello: () => `Hello`,
    rachelsQuery: () => `hello from rachels query`,
  },
  Counter: {
    countStr: counter => `Current count: ${counter.count}`,
  },
  Subscription: {
    counter: {
      subscribe: (parent, args, { pubsub }) => {
        const channel = Math.random().toString(36).substring(2, 15) // random channel name
        let count = 0
        setInterval(() => pubsub.publish(channel, { counter: { count: count++ } }), 2000)
        return pubsub.asyncIterator(channel)
      },
    }
  }
}
// ./graphql/types/types.graphql
type Query {
    hello: String!
    rachelsQuery: String!
}
type Counter {
    count: Int!
    countStr: String
}
type Subscription {
    counter: Counter!
}

// graphiql web playground error
{
  "data": null,
  "error": [
    {
      "message": "Cannot use GraphQLSchema \"[object Object]\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results."
    }
  ]
}
```

![capture](https://user-images.githubusercontent.com/17103917/35529329-efb803e6-04ed-11e8-80a2-5c3a2f8d89c1.PNG)

**Comment by cfnelson** [comment] 2018-01-29 19:31
@davidjohnbell It sounds like you might have two different versions of `graphql` installed? At least from that error. Might be another package has `graphql` as a direct dependency? 

However potentially another quick solution to test would be to swap out the graphql 0.11.7 with the specific github npm branch which is not yet published. `yarn add graphql@git://github.com/graphql/graphql-js.git#npm`.

**Comment by davidjohnbell** [comment] 2018-01-29 19:40
@cfnelson thank you for your speedy reply. I tried the pulling from their git previously and got the same error as above. Could there be some sort of error specific using graphql-yoga? This was my package and if I deleted the node modules and installed using `npm install` I still get the error.

``` JavaScript
{
    //...Omitted for brevity

    "dependencies": {
        "express": "^4.16.2",
        "graphql": "0.11.7", //or 0.12.4
        "graphql-yoga": "^1.2.1"
        "merge-graphql-schema": //Latest version num 
    },

    //...Omitted for brevity
}
```

**Comment by cfnelson** [comment] 2018-01-29 20:56
@davidjohnbell I suspect the issue is due to `graphql-yoga` having `graphql: ^0.12.0` as a dependency - see [here](https://github.com/graphcool/graphql-yoga/blob/master/package.json#L46). Hopefully all this is resolved once `0.12.4` is released.

**Comment by arvi** [comment] 2018-01-31 11:36
Right, I had to change `^0.12.3` to `0.11.7` for it to work. :smile: thanks to all.

**Comment by email2vimalraj** [comment] 2018-01-31 18:11
This works fine with the recent release candidate version of graphql - `"graphql": "^0.13.0-rc.1"`.

**Comment by bvitale** [comment] 2018-01-31 18:43
Can also confirm fixed with RC1

**Comment by negezor** [comment] 2018-02-15 14:16
GraphQL v0.13.0 [released](https://github.com/graphql/graphql-js/releases/tag/v0.13.0.)

The `getDescription ` function was returned.

**Comment by MagnusFrater** [comment] 2018-02-17 00:34
Non-broken GraphQL v0.13.0 link: https://github.com/graphql/graphql-js/releases/tag/v0.13.0

PR: https://github.com/graphql/graphql-js/pull/1165

This issue can be closed.

**Comment by RichardLitt** [comment] 2018-02-17 02:33
@MagnusFrater Oughtn't we to update our dep, first?

**Comment by cfnelson** [comment] 2018-02-26 16:31
`v1.5.0` has just been released and resolves this issue if you have installed `graphql v0.13.x`

**Closed by cfnelson** 2018-02-26 16:31 UTC
Labels: question
